# Generated by Django 4.2.20 on 2025-04-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseGitRepo",
            fields=[
                (
                    "course_id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("git_url", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Course Git Repository",
                "verbose_name_plural": "Course Git Repositories",
                "ordering": ["-created_at"],
            },
        ),
    ]
