# Generated by Django 5.2.9 on 2026-01-15 09:18

import opaque_keys.edx.django.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type: ignore[var-annotated]

    operations = [
        migrations.CreateModel(
            name="CourseTranslationLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_course_id",
                    opaque_keys.edx.django.models.CourseKeyField(
                        db_index=True, max_length=255
                    ),
                ),
                (
                    "source_course_language",
                    models.CharField(
                        help_text="Source language code (e.g., 'EN')", max_length=10
                    ),
                ),
                (
                    "target_course_language",
                    models.CharField(
                        help_text="Target language code for translation (e.g., 'FR')",
                        max_length=10,
                    ),
                ),
                (
                    "srt_provider_name",
                    models.CharField(
                        blank=True,
                        help_text="LLM Provider used for SRT translation",
                        max_length=100,
                    ),
                ),
                (
                    "srt_provider_model",
                    models.CharField(
                        blank=True,
                        help_text="LLM provider model used for SRT translation",
                        max_length=100,
                    ),
                ),
                (
                    "content_provider_name",
                    models.CharField(
                        blank=True,
                        help_text="LLM Provider used for content translation",
                        max_length=100,
                    ),
                ),
                (
                    "content_provider_model",
                    models.CharField(
                        blank=True,
                        help_text="LLM provider model used for content translation",
                        max_length=100,
                    ),
                ),
                (
                    "command_stats",
                    models.TextField(
                        blank=True, help_text="Logs from the translation command"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
