# Generated by Django 5.2 makemigrations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ol_openedx_course_translations", "0001_add_translation_logs"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationQualityRun",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        db_index=True,
                        help_text="Target language code for this run",
                        max_length=10,
                    ),
                ),
                (
                    "benchmark_fixture",
                    models.CharField(
                        help_text="Benchmark file this run translated", max_length=255
                    ),
                ),
                (
                    "translators_arg",
                    models.TextField(help_text="--translators roster as supplied"),
                ),
                (
                    "judges_arg",
                    models.TextField(help_text="--judges roster as supplied"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TranslationQualityCandidate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "translator",
                    models.CharField(
                        help_text="Provider/model that translated", max_length=200
                    ),
                ),
                (
                    "validator",
                    models.CharField(
                        blank=True,
                        help_text="Provider/model that reviewed; blank if none",
                        max_length=200,
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="Why this candidate was excluded, if it was",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="ol_openedx_course_translations.translationqualityrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranslationQualityScore",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judge",
                    models.CharField(
                        help_text="Provider/model that scored this candidate",
                        max_length=200,
                    ),
                ),
                (
                    "accuracy",
                    models.PositiveSmallIntegerField(
                        help_text="Meaning preserved, 1-10"
                    ),
                ),
                (
                    "fluency",
                    models.PositiveSmallIntegerField(
                        help_text="Reads naturally to a native reader, 1-10"
                    ),
                ),
                (
                    "terminology",
                    models.PositiveSmallIntegerField(
                        help_text="Terms and proper nouns handled, 1-10"
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True, help_text="One-sentence rationale the judge gave"
                    ),
                ),
                (
                    "comparative_rank",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Rank within the shortlist; null if not shortlisted",
                        null=True,
                    ),
                ),
                (
                    "comparative_label",
                    models.CharField(
                        blank=True,
                        help_text="Anonymized label this judge saw while ranking",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="ol_openedx_course_translations.translationqualitycandidate",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="translationqualitycandidate",
            constraint=models.UniqueConstraint(
                fields=("run", "translator", "validator"),
                name="unique_candidate_per_run",
            ),
        ),
        migrations.AddConstraint(
            model_name="translationqualityscore",
            constraint=models.UniqueConstraint(
                fields=("candidate", "judge"),
                name="unique_score_per_candidate_and_judge",
            ),
        ),
    ]
