# Generated by Django 6.0.3 on 2026-09-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ol_openedx_course_translations", "0002_add_translation_quality_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationqualitycandidate",
            name="translated_content",
            field=models.TextField(
                blank=True,
                help_text="This arm's translated OLX, blank if the arm failed",
            ),
        ),
    ]
