# Generated by Django 5.2.6 on 2025-09-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapid_response_xblock', '0005_remove_run_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapidresponsesubmission',
            name='event',
            field=models.JSONField(),
        ),
    ]
