# Generated by Django 5.2.15 on 2026-09-14 12:29

import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type: ignore[var-annotated]

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "short_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "short_code may contain only letters, "
                                    "numbers, and the characters _ - ~ . : "
                                    "(it is embedded directly into the "
                                    "generated course key)."
                                ),
                                regex="\\A[\\w\\-~.:]*\\Z",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Industries",
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="unique_industry_name_ci",
                    ),
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("short_code"),
                        name="unique_industry_short_code_ci",
                    ),
                ],
            },
        ),
    ]
