# Generated by Django 5.2 for ol_openedx_uai_content_customization

from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type: ignore[var-annotated]

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("short_code", models.CharField(blank=True, max_length=10)),
            ],
            options={
                "verbose_name_plural": "Industries",
            },
        ),
        migrations.AddConstraint(
            model_name="industry",
            constraint=models.UniqueConstraint(
                Lower("name"), name="unique_industry_name_ci"
            ),
        ),
        migrations.AddConstraint(
            model_name="industry",
            constraint=models.UniqueConstraint(
                Lower("short_code"), name="unique_industry_short_code_ci"
            ),
        ),
    ]
