# Generated by Django 5.2 for ol_openedx_uai_content_customization
#
# The short_code validator here is a snapshot of Industry.short_code's
# validators=[...] at generation time, kept in sync by `makemigrations`
# rather than by hand — edit models.py, then regenerate, don't patch it
# here directly.

import django.core.validators
from django.db import migrations, models
from django.db.models.functions import Lower


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type: ignore[var-annotated]

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "short_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "short_code may contain only letters, "
                                    "numbers, and the characters _ - ~ . : "
                                    "(it is embedded directly into the "
                                    "generated course key)."
                                ),
                                regex="^[\\w\\-~.:]*$",
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Industries",
            },
        ),
        migrations.AddConstraint(
            model_name="industry",
            constraint=models.UniqueConstraint(
                Lower("name"), name="unique_industry_name_ci"
            ),
        ),
        migrations.AddConstraint(
            model_name="industry",
            constraint=models.UniqueConstraint(
                Lower("short_code"), name="unique_industry_short_code_ci"
            ),
        ),
    ]
