# Generated by Django 4.2.23 on 2025-09-26 14:04

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('edx_sysadmin', '0001_course_git_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegitlog',
            name='course_import_log',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
