# Generated by Django 5.2.6 on 2025-09-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edx_sysadmin", "0001_course_git_log"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursegitlog",
            name="course_import_log",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
