# Generated by Django 4.2.20 on 2025-05-19 06:50

import opaque_keys.edx.django.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type: ignore[var-annotated]

    operations = [
        migrations.CreateModel(
            name="CourseSyncMap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_course",
                    opaque_keys.edx.django.models.CourseKeyField(
                        max_length=255, unique=True
                    ),
                ),
                (
                    "target_courses",
                    models.TextField(
                        blank=True,
                        help_text="Comma separated list of target course keys",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseSyncParentOrg",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
