# Generated by Django 4.2.20 on 2025-05-20 13:12

import opaque_keys.edx.django.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type: ignore[var-annotated]

    operations = [
        migrations.CreateModel(
            name="CourseRunSyncMap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_course",
                    opaque_keys.edx.django.models.CourseKeyField(max_length=255),
                ),
                (
                    "target_course",
                    opaque_keys.edx.django.models.CourseKeyField(
                        max_length=255, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CourseSyncOrganization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
