# Generated by Django 4.2.23 on 2025-09-23 17:17

import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []  # type: ignore  # noqa: PGH003

    operations = [
        migrations.CreateModel(
            name="CourseGithubRepository",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "course_id",
                    opaque_keys.edx.django.models.CourseKeyField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("git_url", models.CharField(max_length=255)),
                ("is_export_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Course Github Repository",
                "verbose_name_plural": "Course Github Repositories",
                "ordering": ["-created"],
            },
        ),
    ]
